"""
brain/intent_data.py — Labeled training dataset for the Nexus intent classifier.

Each entry is a (phrase, intent) tuple.
Add more phrases to improve accuracy for any intent.
"""

TRAINING_DATA = [

    # ── OPEN_BROWSER ──────────────────────────────────────────────────────────
    ("open chrome", "OPEN_BROWSER"),
    ("launch chrome", "OPEN_BROWSER"),
    ("open google chrome", "OPEN_BROWSER"),
    ("start chrome", "OPEN_BROWSER"),
    ("open the browser", "OPEN_BROWSER"),
    ("launch browser", "OPEN_BROWSER"),
    ("start the browser", "OPEN_BROWSER"),
    ("I want to surf the web", "OPEN_BROWSER"),
    ("surf the internet", "OPEN_BROWSER"),
    ("browse the web", "OPEN_BROWSER"),
    ("open internet", "OPEN_BROWSER"),
    ("go online", "OPEN_BROWSER"),
    ("open edge", "OPEN_BROWSER"),
    ("launch microsoft edge", "OPEN_BROWSER"),
    ("open a website", "OPEN_BROWSER"),
    ("I need to search something online", "OPEN_BROWSER"),
    ("take me to the internet", "OPEN_BROWSER"),
    ("open my browser", "OPEN_BROWSER"),
    ("fire up chrome", "OPEN_BROWSER"),
    ("get me online", "OPEN_BROWSER"),

    # ── OPEN_NOTEPAD ──────────────────────────────────────────────────────────
    ("open notepad", "OPEN_NOTEPAD"),
    ("launch notepad", "OPEN_NOTEPAD"),
    ("start notepad", "OPEN_NOTEPAD"),
    ("I need a text editor", "OPEN_NOTEPAD"),
    ("open text editor", "OPEN_NOTEPAD"),
    ("I want to write something", "OPEN_NOTEPAD"),
    ("open a writing app", "OPEN_NOTEPAD"),
    ("let me type something", "OPEN_NOTEPAD"),
    ("need to jot something down", "OPEN_NOTEPAD"),
    ("open the notepad app", "OPEN_NOTEPAD"),
    ("I want to take notes", "OPEN_NOTEPAD"),
    ("open a new text file", "OPEN_NOTEPAD"),
    ("start a blank document", "OPEN_NOTEPAD"),
    ("I need to draft something", "OPEN_NOTEPAD"),
    ("quick note please", "OPEN_NOTEPAD"),
    ("open writing tool", "OPEN_NOTEPAD"),
    ("notepad please", "OPEN_NOTEPAD"),
    ("just open notepad", "OPEN_NOTEPAD"),
    ("bring up notepad", "OPEN_NOTEPAD"),
    ("open simple text editor", "OPEN_NOTEPAD"),

    # ── OPEN_CALCULATOR ───────────────────────────────────────────────────────
    ("open calculator", "OPEN_CALCULATOR"),
    ("launch calculator", "OPEN_CALCULATOR"),
    ("start calculator", "OPEN_CALCULATOR"),
    ("I need to crunch some numbers", "OPEN_CALCULATOR"),
    ("do some math", "OPEN_CALCULATOR"),
    ("I need to calculate something", "OPEN_CALCULATOR"),
    ("can you open the calc", "OPEN_CALCULATOR"),
    ("I need math help", "OPEN_CALCULATOR"),
    ("bring up the calculator", "OPEN_CALCULATOR"),
    ("let me do some calculations", "OPEN_CALCULATOR"),
    ("open the calc app", "OPEN_CALCULATOR"),
    ("I need to add some numbers", "OPEN_CALCULATOR"),
    ("calculator please", "OPEN_CALCULATOR"),
    ("open math tool", "OPEN_CALCULATOR"),
    ("I want to calculate", "OPEN_CALCULATOR"),
    ("open calc", "OPEN_CALCULATOR"),
    ("number cruncher", "OPEN_CALCULATOR"),
    ("I need to divide something", "OPEN_CALCULATOR"),
    ("help me with arithmetic", "OPEN_CALCULATOR"),
    ("quick calculation needed", "OPEN_CALCULATOR"),

    # ── OPEN_VSCODE ───────────────────────────────────────────────────────────
    ("open vs code", "OPEN_VSCODE"),
    ("launch vs code", "OPEN_VSCODE"),
    ("start visual studio code", "OPEN_VSCODE"),
    ("open my code editor", "OPEN_VSCODE"),
    ("open the code editor", "OPEN_VSCODE"),
    ("I want to code", "OPEN_VSCODE"),
    ("launch my IDE", "OPEN_VSCODE"),
    ("open visual studio code", "OPEN_VSCODE"),
    ("bring up vscode", "OPEN_VSCODE"),
    ("I need to write some code", "OPEN_VSCODE"),
    ("open my python editor", "OPEN_VSCODE"),
    ("start coding", "OPEN_VSCODE"),
    ("open the developer editor", "OPEN_VSCODE"),
    ("let me program something", "OPEN_VSCODE"),
    ("I want to write a script", "OPEN_VSCODE"),
    ("fire up vs code", "OPEN_VSCODE"),
    ("code editor please", "OPEN_VSCODE"),
    ("open programming editor", "OPEN_VSCODE"),
    ("launch code", "OPEN_VSCODE"),
    ("I need my coding environment", "OPEN_VSCODE"),

    # ── OPEN_FOLDER ───────────────────────────────────────────────────────────
    ("open downloads folder", "OPEN_FOLDER"),
    ("show downloads", "OPEN_FOLDER"),
    ("go to downloads", "OPEN_FOLDER"),
    ("open documents", "OPEN_FOLDER"),
    ("open my documents folder", "OPEN_FOLDER"),
    ("show me my files", "OPEN_FOLDER"),
    ("open file explorer", "OPEN_FOLDER"),
    ("open my project folder", "OPEN_FOLDER"),
    ("go to my python project", "OPEN_FOLDER"),
    ("navigate to desktop", "OPEN_FOLDER"),
    ("open the desktop folder", "OPEN_FOLDER"),
    ("open pictures folder", "OPEN_FOLDER"),
    ("bring up file manager", "OPEN_FOLDER"),
    ("show my storage", "OPEN_FOLDER"),
    ("open nexus storage", "OPEN_FOLDER"),
    ("open storage folder", "OPEN_FOLDER"),
    ("navigate to downloads", "OPEN_FOLDER"),
    ("show documents folder", "OPEN_FOLDER"),
    ("open my files", "OPEN_FOLDER"),
    ("go to project directory", "OPEN_FOLDER"),

    # ── SAVE_TEXT ─────────────────────────────────────────────────────────────
    ("save this text", "SAVE_TEXT"),
    ("save this note", "SAVE_TEXT"),
    ("remember this", "SAVE_TEXT"),
    ("store this information", "SAVE_TEXT"),
    ("keep this text", "SAVE_TEXT"),
    ("write this down", "SAVE_TEXT"),
    ("save this to my ideas", "SAVE_TEXT"),
    ("save this to ideas folder", "SAVE_TEXT"),
    ("note this down", "SAVE_TEXT"),
    ("store a file for me", "SAVE_TEXT"),
    ("create a text file with this", "SAVE_TEXT"),
    ("save my idea", "SAVE_TEXT"),
    ("I want to save some text", "SAVE_TEXT"),
    ("make a note of this", "SAVE_TEXT"),
    ("keep a record of this", "SAVE_TEXT"),
    ("archive this text", "SAVE_TEXT"),
    ("save this memo", "SAVE_TEXT"),
    ("I have an idea I want to save", "SAVE_TEXT"),
    ("write a note for me", "SAVE_TEXT"),
    ("create a note", "SAVE_TEXT"),

    # ── FIND_FILE ─────────────────────────────────────────────────────────────
    ("where did I put my file", "FIND_FILE"),
    ("find my presentation", "FIND_FILE"),
    ("where is my document", "FIND_FILE"),
    ("locate my file", "FIND_FILE"),
    ("search for my notes", "FIND_FILE"),
    ("where did I save my ideas", "FIND_FILE"),
    ("find my project file", "FIND_FILE"),
    ("I can't find my file", "FIND_FILE"),
    ("help me find a document", "FIND_FILE"),
    ("where is my text file", "FIND_FILE"),
    ("look for my notes", "FIND_FILE"),
    ("search my storage", "FIND_FILE"),
    ("find the file I saved", "FIND_FILE"),
    ("where did I put that presentation", "FIND_FILE"),
    ("locate my presentation", "FIND_FILE"),
    ("find a document for me", "FIND_FILE"),
    ("search for my saved files", "FIND_FILE"),
    ("I need to find something I saved", "FIND_FILE"),
    ("can you find my file", "FIND_FILE"),
    ("where are my files", "FIND_FILE"),

    # ── CREATE_FOLDER ─────────────────────────────────────────────────────────
    ("create a new folder", "CREATE_FOLDER"),
    ("make a new folder", "CREATE_FOLDER"),
    ("make a directory", "CREATE_FOLDER"),
    ("create a folder called Vacation", "CREATE_FOLDER"),
    ("new folder please", "CREATE_FOLDER"),
    ("I want to create a directory", "CREATE_FOLDER"),
    ("set up a new folder", "CREATE_FOLDER"),
    ("create folder", "CREATE_FOLDER"),
    ("make directory", "CREATE_FOLDER"),
    ("mkdir Vacation", "CREATE_FOLDER"),
    ("build a new folder", "CREATE_FOLDER"),
    ("I need a new folder", "CREATE_FOLDER"),
    ("create a new directory", "CREATE_FOLDER"),
    ("set up a folder for me", "CREATE_FOLDER"),
    ("organize my files into a new folder", "CREATE_FOLDER"),
    ("create a project folder", "CREATE_FOLDER"),
    ("make me a folder", "CREATE_FOLDER"),
    ("create a folder for my project", "CREATE_FOLDER"),
    ("I want a new folder called Work", "CREATE_FOLDER"),
    ("make a folder named ideas", "CREATE_FOLDER"),

    # ── RUN_COMMAND ───────────────────────────────────────────────────────────
    ("run a command", "RUN_COMMAND"),
    ("execute a script", "RUN_COMMAND"),
    ("run terminal command", "RUN_COMMAND"),
    ("execute this command", "RUN_COMMAND"),
    ("run this in the terminal", "RUN_COMMAND"),
    ("run my python script", "RUN_COMMAND"),
    ("execute python file", "RUN_COMMAND"),
    ("run bash command", "RUN_COMMAND"),
    ("open terminal and run", "RUN_COMMAND"),
    ("I need to run a script", "RUN_COMMAND"),
    ("execute a program", "RUN_COMMAND"),
    ("run the program", "RUN_COMMAND"),
    ("execute my code", "RUN_COMMAND"),
    ("run the script", "RUN_COMMAND"),
    ("run command please", "RUN_COMMAND"),
    ("launch script", "RUN_COMMAND"),
    ("I want to run something", "RUN_COMMAND"),
    ("can you execute a file", "RUN_COMMAND"),
    ("please run this command", "RUN_COMMAND"),
    ("run system command", "RUN_COMMAND"),

    # ── WEB_SEARCH ────────────────────────────────────────────────────────────
    ("search for python tutorials", "WEB_SEARCH"),
    ("google how to cook pasta", "WEB_SEARCH"),
    ("search online for weather today", "WEB_SEARCH"),
    ("find best hotels in Paris on the web", "WEB_SEARCH"),
    ("search chrome for latest news", "WEB_SEARCH"),
    ("look up machine learning on google", "WEB_SEARCH"),
    ("search the web for funny cat videos", "WEB_SEARCH"),
    ("google search artificial intelligence", "WEB_SEARCH"),
    ("look for recipes online", "WEB_SEARCH"),
    ("search for movies near me", "WEB_SEARCH"),
    ("find information about space travel", "WEB_SEARCH"),
    ("search for a restaurant", "WEB_SEARCH"),
    ("how do I fix a broken car", "WEB_SEARCH"),
    ("what is the capital of France", "WEB_SEARCH"),
    ("search for coding tips", "WEB_SEARCH"),
    ("google search", "WEB_SEARCH"),
    ("look up on the web", "WEB_SEARCH"),
    ("search", "WEB_SEARCH"),
    ("find on the internet", "WEB_SEARCH"),
    ("google this", "WEB_SEARCH"),

    # ── PLAY_MEDIA ────────────────────────────────────────────────────────────
    ("play music on youtube", "PLAY_MEDIA"),
    ("search youtube for lo-fi beats", "PLAY_MEDIA"),
    ("watch latest trailer on youtube", "PLAY_MEDIA"),
    ("play some jazz on youtube", "PLAY_MEDIA"),
    ("search for funny videos on youtube", "PLAY_MEDIA"),
    ("play something on youtube", "PLAY_MEDIA"),
    ("watch music videos", "PLAY_MEDIA"),
    ("open youtube and search for coding tutorials", "PLAY_MEDIA"),
    ("play a song", "PLAY_MEDIA"),
    ("watch a video on youtube", "PLAY_MEDIA"),
    ("search youtube", "PLAY_MEDIA"),
    ("play media", "PLAY_MEDIA"),
    ("play a movie trailer", "PLAY_MEDIA"),
    ("listen to music online", "PLAY_MEDIA"),
    ("play viral videos", "PLAY_MEDIA"),

    # ── GOODBYE ───────────────────────────────────────────────────────────────
    ("goodbye", "GOODBYE"),
    ("goodbye nexus", "GOODBYE"),
    ("bye", "GOODBYE"),
    ("bye nexus", "GOODBYE"),
    ("exit", "GOODBYE"),
    ("quit", "GOODBYE"),
    ("stop listening", "GOODBYE"),
    ("shut down nexus", "GOODBYE"),
    ("turn off nexus", "GOODBYE"),
    ("close nexus", "GOODBYE"),
    ("I'm done", "GOODBYE"),
    ("that's all", "GOODBYE"),
    ("see you later", "GOODBYE"),
    ("stop", "GOODBYE"),
    ("stop the assistant", "GOODBYE"),
    ("deactivate", "GOODBYE"),
    ("go to sleep", "GOODBYE"),
    ("sleep mode", "GOODBYE"),
    ("I don't need you anymore", "GOODBYE"),
    ("you can stop now", "GOODBYE"),
]
